### ISSUE TITLE
Support booleans with symbolic names?

### ISSUE THREAD

**Issue by kentborg** [bodil/bitmaps#28]
I'm unnerved by passing around naked booleans, for fear the sense will be misinterpreted, incompatible boolean parameters silently swapped, etc.

Could there be a sensible way to allow symbolic values to be used in a `bitmap`?

In my case, to represent whether a pushbutton key is pressed or not, I defined:
```
pub enum KeyPosition {
    Up,
    Down,
}
```

But to use this in a `bitmap` I have to keep converting to and from `bool`. Could `bitmap` be extended to hold something like my enum? (Or is this possible already and I don't spot it?)

Thanks,

-kb

**Comment by flinesse** [comment]
I'm not sure whether it's possible to directly retrieve a stored bit as some user-defined, binary enum discriminant—but I find `const` sufficient for this purpose:

```rust
pub const KEY_UP: bool = false;
pub const KEY_DOWN: bool = true;
```

**Comment by bodil** [comment]
I can see this being straightforward to implement using a conversion trait, but the scope of this crate is more that of something you could build on top of to achieve that, so I'll close this.
