### ISSUE TITLE
Add as_value() method

### ISSUE THREAD

**Issue by lerouxrgd** [bodil/bitmaps#7]
Hello,

Would it be possible to have a method `as_value()` on `Bitmap` ?

I guess the implementation would simply be:

```rust
    pub fn as_value(&self) -> &Size::Store {
        &self.data
    }
```

Besides, the reason I am trying to get the underlying value is to be able to implement `PartialOrd`, `Eq`, `Ord`, and `Hash` on a custom type that uses a `Bitmap`.
Is there any reason why those implementations are not available out of the box even though the underlying value implement them ?

**Comment by bodil** [comment]
I suppose the only reason there are no `Eq`, `Ord` etc implementations is that I didn't need them at the time. Seems like a good time to add them as well as the `as_value` method (although I'm not sure that's the best name, let me see if I can think of a better one as I implement it).

**Comment by bodil** [comment]
Oh wait, never mind, I already used `into_value()` etc, guess it's not a good idea to change that.

**Comment by lerouxrgd** [comment]
Thank you !
